---
blank_issues_enabled: false
contact_links:
  - name: Monero Python Database Reader Community Support
    url: https://github.com/AnonimaUzanto/pymonerodb/discussions
    about: Please ask and answer questions here.
